title: 김하연의 포폴사이트
name: 김하연
email: chocokakao@naver.com
description: >-
  Data Scientist & A.I developer


baseurl: ""
url: "https://hayeon31.github.io"


# profile 이미지
profile_image: images/about.jpg


# SNS 아이디
facebook_id: 
instagram_id: 


# Youtube vid
youtube_vid: #


# Custom Color
primary: 2c98f0 #b72cf0
primary_hover: ec5453 #44A4F2 #9a2dc7
color_1: 2c98f0 #b72cf0
color_2: ec5453
color_3: f9bf3f
color_4: a84cb8
color_5: 2fa499
color_6: 4054b2


# slider type 0  (텍스트가 우측 정렬된 슬라이더)
slider_0: # 형식에 맞추어 항목 추가
- background_url: images/cover_bg_4.jpg
  title: I am<br>AI Developer
  subtitle: >- 
    hi<br>
    im<br>
    hayeon<br>
    and U?
  position : absolute
  transform : translate( -50%, -50%)
  left: 50px
  bottom: 50px




# - background_url: images/cover_bg_3.jpeg
#   title: Hi. <br>How R U?</br>
#   subtitle:
#   position : absolute
#   transform : translate( -50%, -50%)
#   left: 80px
#   bottom: 0px

# slider_0_color : rgb(255,255,255)


# slider type 1  (텍스트가 좌측 정렬된 슬라이더)
slider_1: # 형식에 맞추어 항목 추가
- background_url: images/img_bg_3_.jpeg
  title: Hi. <br>My Name is HayeonKIM</br>
  subtitle: 
  position : absolute
  transform : translate( -50%, -50%)
  left: 600px
  bottom: 400px

  slider_0_color : rgb(255,255,255)




# About
about_meta: About Me
about_header: >- 
  "무엇이든 오래 고민하던 대학생"
about_introduce: >-
  "안녕하세요 인공지능 전문가를 꿈꾸는, 늘 도전하는 김하연입니다 ."
about_content: >-
  <strong></strong> 
about_services: # 형식에 맞추어 항목 추가
- icon: icon-data
  name: Server
- icon: icon-monitor
  name: Web
- icon: icon-phone3
  name: App
- icon: icon-code
  name: Python
about_box_content: >-
  "다른 사람의 의견이 너의 현실이 될 필요는 없다." -레스 브라운-<br><br>
  
  안될 거라는 말을 듣기보다,<br><br>해낼 수 있다라고 믿는 사람입니다.<br><br>
  
about_box_button:
  link: #
  name: >-
    You Can Do IT


# Tech  skill
tech_meta: TECH SKILLS
tech_header: 저는 현재 이것을 할 수 있습니다.
# tech_content: markdown으로 할수 있으면 좋을듯
tech_list: # 형식에 맞추어 항목 추가
- name: Python
  color: color-1
  animation: fadeInLeft
  percent: 35
  mark: 35 # 이게 바를 조정한다.
  content: 파이썬 기초, 데이터 분석과 시각화를 공부하고 파이썬 언어의 기본적인 문법에 대해 알고 있으며, 자료구조 및 알고리즘을 파이썬으로 공부하였습니다.
- name: 머신러닝
  color: color-3
  animation: fadeInRight
  percent: 15
  mark: 25
  content: 공부하면 공부할수록 이 분야가 정말 방대하고 제가 아는것이 정말 일부분이라는 것을 많이 느낍니다. 통계 이론부터 다시 배우겠다는 마음으로 공부하고 있습니다.
- name: 딥러닝
  color: color-2
  animation: fadeInLeft
  percent: 15
  mark: 20
  content: 공부하면 공부할수록 이 분야가 정말 방대하고 제가 아는것이 정말 일부분이라는 것을 많이 느낍니다. 통계 이론부터 다시 배우겠다는 마음으로 공부하고 있습니다.
- name: Github
  color: color-4
  animation: fadeInRight
  percent: 25
  mark: 25
  content: 대부분의 프로젝트를 github를 통해 소스 코드를 관리하였으며, 협업 역시 github을 통해 진행하였습니다. 또한 github서버를 활용하여 블로그 및 포트폴리오 사이트를 관리합니다.
tech_desc: AI 전문가가 되기 위해서 <strong>Python, 머신러닝, 딥러닝 </strong>에 집중할 생각입니다. 


# Project
project_meta: My Work
project_header: PROJECT
project_introduce: <span>개인 프로젝트</span><span>팀 프로젝트</span>
project_load_more: 앞으로 더 많은 프로젝트가 추가될 예정입니다:)    # 더보기 내용
project_load_more_url: #

project_my_name: 개인프로젝트

project_my: # 형식에 맞추어 항목 추가
- background_url: images/budong.jpg
  animation: fadeInLeft
  name: 서울 부동산가격 예측 프로젝트 (2021.11)
  description:  
  detail_url: #
  readmore_url: https://github.com/HayeonKimm/machine-Learning/blob/master/machine-pjt/My_Project/%EC%84%9C%EC%9A%B8_%EC%A3%BC%ED%83%9D%EA%B0%80%EA%B2%A9_%EC%98%88%EC%B8%A1%ED%95%98%EA%B8%B0.ipynb

# - background_url: 
#   animation: fadeInLeft
#   name: 
#   description: 
  # detail_url: #
  # readmore_url: #/






project_team_name: 팀프로젝트
project_team: # 형식에 맞추어 항목 추가
- background_url: images/covid.png
  animation: fadeInRight
  name: XGBoost를 활용한 코로나19 예측
  description: 
  detail_url: pdf/covid.pdf
  readmore_url: pdf/annae.pdf

# project_team_name: 팀프로젝트
# project_team: # 형식에 맞추어 항목 추가
- background_url: images/jeju.png
  animation: fadeInRight
  name: 제주도 관광객 소비 패턴 분석 프로젝트
  description: 
  detail_url: pdf/jeju.pdf
  readmore_url: https://github.com/HayeonKimm/Tourist_Consumption_Analysis

- background_url: images/bus.png
  animation: fadeInRight
  name: 머신러닝을 활용한 버스도착시간 예측 모델
  description: 
  detail_url: pdf/bus.pdf
  readmore_url: https://github.com/HayeonKimm/bus-time-prediction


- background_url: images/traffic.png
  animation: fadeInRight
  name: 교통 데이터를 활용한 웹서비스 프로젝트
  description: 
  detail_url: pdf/traffic.pdf
  readmore_url: https://github.com/HayeonKimm/Traffic-Webservice-1

# project_business_name: Business
# project_business: # 형식에 맞추어 항목 추가
# - background_url: 
#   animation: fadeInTop
#   name: 
#   description: >-

#   detail_url: #
#   readmore_url: #


# Experience
exp_meta: What have I achieved?
exp_header: 저는 이런 "경험"들을 해봤습니다.
exp_content: 회사에서 필요로 한다면 이런 역량도 가지고 있습니다.
exp_services: # 형식에 맞추어 항목 추가
- name: 아이디어
  color: color-1
  icon: icon-bulb
  content: INTP의 특징인 아이디어 뱅크 특성을 가졌습니다. 팀원들의 브레인 스토밍과 아이디어 디벨롭을 돕습니다.
- name: 기술습득
  color: color-2
  icon: icon-home
  content: 제가 선택한 길, 항상 열정을 다해 공부하며 새로운 기술에 대해 즐거운 마음으로 배웁니다.
- name: 프로젝트
  color: color-3
  icon: icon-phone3
  content: 다양한 프로젝트를 기획, 진행 해왔기에 업무에 대한 협력과 배분이 익숙합니다. 새로운 프로젝트에 도전적입니다.
exp_counters:
- name: 개발 공부시작 (DAY)
  count: 197
  speed: 10000
- name: project (NUMBER)
  count: 6
  speed: 10000


# Career
# carerr_meta: career
# career_header: Work Career
# career_list:
# - name: 과기전통부 산학과제
#   date: 2020.06~2020.11
#   content: PlenOPtic Video에서 객체 tracking 연구  <br> 중대형 공간용 초고해상도 비정형 플렌옵틱 동영상 저작/재생 플랫폼 기술 개발
#   color: color-1
#   icon: icon-pen2
#   animation: fadeInLeft
# - name: Voice Caddie 산학과제
#   date: 2021.05~2021.10
#   content: 현재 골프치는 사람의 Pose와 Multi-view를 연구하고 있습니다.
#   color: color-2
#   icon: icon-pen2
#   animation: fadeInRight


# Education
edu_meta: Education
edu_header: Education
edu_list:
- title: HONGIK UNIVERSITY URBAN ENGINEERING AND PLANING BACHELOR
  subtitle: 홍익대학교 도시공학과 졸업
  date: 2015.02 - 2021.08
  content: 
- title: SAMSUNG MULTICAMPUS
  subtitle: 데이터 사이언스 & 엔지니어링
  date: 2021.05 - 2021.10
  content: 
- title: NIPA
  subtitle: AI 기본 & 실무 과정
  date: 2021.08 - 2021.11
  content: >-
   
- title: 멋쟁이 사자처럼 X SOCAR
  subtitle: AI 엔지니어 육성 과정
  date: 2021.10 - 2022.01
  content: >-


# # Blog
# blog_meta: self-improvement
# blog_header: BLOG and YOUTUBE
# blog_load_more: 더 발전하기 위해 항상 노력합니다    # 더보기 내용
# blog_load_more_url: #
# blog_list:
# - title: 아기치타의 AI 대학원 블로그
#   subtitle: 개발 블로그 운영
#   date: 2021.01
#   content: 여러 분야의 프로그래머들을 보면서 부러워도 하고 좌절도 하였지만 포기하지않고 어느 한분야라도 '장인'이 되겠다는 마음으로 꾸준히 개발 블로그를 운영해오고 있습니다.
#   thumbnail_url: images/blog-1.PNG
#   link: #
# - title: 따라쟁이의 유튜브
#   subtitle: 개발,논문 유튜브 채널 운영
#   date: 2018.04
#   content: 유튜브 채널을 운영하며 배운 것들을 정리해서 영상을 촬영하고 있습니다. 개인적으로 복습을 한번 더 하는 장점이 있습니다.
#   thumbnail_url: images/blog-2.PNG
#   link: #
# - title: 네이버블로그
#   subtitle: 이전 블로그
#   date: 2018.03
#   content: 막 복학을하고 전과했을때 시작했던 첫블로그입니다.
#   thumbnail_url: images/blog-3.PNG
#   link: #


#Contact
contact_meta: Get in Touch
contact_header: Contact
contact_list:
- title: 이메일
  icon: icon-globe-outline
  url: hayeon.data@gmail.com
# - title: 
#   icon: icon-map
# - title: 
#   icon: icon-phone
- title: Github 링크
  icon: icon-layers2
  url: https://github.com/HayeonKimm
contact_message: <em>연락해주셔서 감사합니다.</em> 24시간이내에 회신드리도록 하겠습니다. :)


optional_front_matter:
  remove_originals:    true
